CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_STDOUT_CONSOLE=n
CONFIG_EARLY_CONSOLE=n
CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n

CONFIG_MBOX=y
CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_BACKEND_ICMSG=y
CONFIG_ASSERT=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_IPC_SERVICE_BACKEND_ICMSG_WQ_STACK_SIZE=2048
CONFIG_PBUF_RX_READ_BUF_SIZE=256
