CONFIG_RF_LINK_FUTURE_MODE=y
CONFIG_RF_LINK_RADIO_QUEUE_DEPTH=64
CONFIG_RF_LINK_FRAME_QUEUE_DEPTH=64
CONFIG_RF_LINK_NODE_ID=0

CONFIG_RF_LINK_SYNC_MANAGER=y
CONFIG_RF_LINK_SYNC_HW_CAPTURE=y
CONFIG_RF_LINK_SYNC_TIMEOUT_MS=1500
CONFIG_RF_LINK_SYNC_LARGE_GAP_FRAMES=256

CONFIG_RF_LINK_FPGA_TRANSPORT=y
CONFIG_RF_LINK_FPGA_SPIS=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_CRC=y

CONFIG_NRFX_TIMER20=y
CONFIG_NRFX_GPPI=y
CONFIG_NRFX_GPIOTE20=y

CONFIG_RF_LINK_FPGA_SPIS_THREAD_STACK_SIZE=3072
CONFIG_RF_LINK_FPGA_SPIS_THREAD_PRIORITY=5
