CONFIG_RF_LINK_FUTURE_MODE=y
CONFIG_RF_LINK_RADIO_QUEUE_DEPTH=64
CONFIG_RF_LINK_FRAME_QUEUE_DEPTH=64
CONFIG_RF_LINK_NODE_ID=0

CONFIG_RF_LINK_SYNC_MANAGER=y
CONFIG_RF_LINK_SYNC_HW_CAPTURE=n
CONFIG_RF_LINK_FPGA_TRANSPORT=n
CONFIG_CRC=y
