CONFIG_RF_LINK_RX_SAMPLE_STREAM=y
CONFIG_RF_LINK_RX_SAMPLE_STREAM_UART_BAUD=2000000
CONFIG_RF_LINK_RX_SAMPLE_STREAM_BUFFERED_RECORDS=32
CONFIG_RF_LINK_RX_SAMPLE_STREAM_THREAD_STACK_SIZE=2048
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
